### ISSUE TITLE
build not completing

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/lewis-carroll_through-the-looking-glass_john-tenniel#4]
I pushed an update to the longdesc with a new link, but the site didn’t update. Running a test build just hangs on both my latest commit, and the previous commit. Unfortunately I’m having difficulty in narrowing down in the tools what’s causing it, so first question: is this something you can replicate?

**Comment by robinwhittleton** [comment]
To add: this now appears to have blocked the SE release queue as further changes I’ve made to other books have not appeared 😐

**Comment by acabal** [comment]
Build completes, just very slowly for this one and for Ulysses S. Grant. It has to do with the SVGs. I'm not sure exactly why but those two books take 1 hour+ to build on the server. It's kind of crappy but I don't have time to look in to how to improve that right now, and at the end of the day it's not a super huge problem anyway :)

**Comment by robinwhittleton** [comment]
Ah, great :)
